"""basic auth model

Revision ID: 4814369ad5cc
Revises: f3458b927eba
Create Date: 2018-10-16 19:06:58.961599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4814369ad5cc'
down_revision = 'f3458b927eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_exchange_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_exchange_auth')
    # ### end Alembic commands ###
