"""user-uuid

Revision ID: 4d968b6403ad
Revises: 4814369ad5cc
Create Date: 2018-11-19 01:53:34.221939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
import shortuuid

from app.models.user import User


# revision identifiers, used by Alembic.
revision = "4d968b6403ad"
down_revision = "4814369ad5cc"
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    session = Session(bind=conn)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user_exchange_auth", ["id"])
    op.add_column("users", sa.Column("uuid", sa.String(), nullable=True))

    for u in session.query(User).filter_by(uuid=None):
        u.uuid = shortuuid.uuid()
    session.commit()

    op.create_unique_constraint(None, "users", ["uuid"])
    op.alter_column(table_name="users", column_name="uuid", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "uuid")
    op.drop_constraint(None, "user_exchange_auth", type_="unique")
    # ### end Alembic commands ###
