"""empty message

Revision ID: 6c6917015a3c
Revises: 7377a3591690
Create Date: 2018-07-24 17:09:47.242789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6917015a3c'
down_revision = '7377a3591690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'strategies', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategies', type_='unique')
    # ### end Alembic commands ###
