"""empty message

Revision ID: b060ded0ae81
Revises: d6722da119b0
Create Date: 2018-07-28 14:08:59.602941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b060ded0ae81'
down_revision = 'd6722da119b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('result_json', sa.JSON(), nullable=True))
    op.drop_column('strategies', 'results_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('results_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('strategies', 'result_json')
    # ### end Alembic commands ###
