"""uuid-fk

Revision ID: c71179d26792
Revises: 4d968b6403ad
Create Date: 2018-11-19 03:05:16.028993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71179d26792'
down_revision = '4d968b6403ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('user_uuid', sa.String(), nullable=True))
    op.drop_constraint('strategies_user_id_fkey', 'strategies', type_='foreignkey')
    op.create_foreign_key(None, 'strategies', 'users', ['user_uuid'], ['uuid'])
    op.drop_column('strategies', 'user_id')
    op.add_column('user_exchange_auth', sa.Column('user_uuid', sa.String(), nullable=True))
    op.drop_constraint('user_exchange_auth_user_id_fkey', 'user_exchange_auth', type_='foreignkey')
    op.create_foreign_key(None, 'user_exchange_auth', 'users', ['user_uuid'], ['uuid'])
    op.drop_column('user_exchange_auth', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exchange_auth', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_exchange_auth', type_='foreignkey')
    op.create_foreign_key('user_exchange_auth_user_id_fkey', 'user_exchange_auth', 'users', ['user_id'], ['id'])
    op.drop_column('user_exchange_auth', 'user_uuid')
    op.add_column('strategies', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.create_foreign_key('strategies_user_id_fkey', 'strategies', 'users', ['user_id'], ['id'])
    op.drop_column('strategies', 'user_uuid')
    # ### end Alembic commands ###
