"""empty message

Revision ID: e3202524923f
Revises: 29498b27f9c4
Create Date: 2018-07-29 02:32:34.601493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3202524923f'
down_revision = '29498b27f9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('trading_config', sa.JSON(), nullable=False),
    sa.Column('dataset_config', sa.JSON(), nullable=False),
    sa.Column('indicators_config', sa.JSON(), nullable=False),
    sa.Column('signals_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategies')
    # ### end Alembic commands ###
