"""empty message

Revision ID: f3458b927eba
Revises: e3202524923f
Create Date: 2018-07-29 03:25:24.358278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3458b927eba'
down_revision = 'e3202524923f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('uuid', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'strategies', ['uuid'])
    op.create_unique_constraint(None, 'strategies', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategies', type_='unique')
    op.drop_constraint(None, 'strategies', type_='unique')
    op.drop_column('strategies', 'uuid')
    # ### end Alembic commands ###
